"""add twitter user table

Revision ID: 7f3b8329ab98
Revises:
Create Date: 2022-12-24 09:53:56.234984+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7f3b8329ab98"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("twitter_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("username", sa.String(length=15), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("following_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("followers_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_twitter_id"), "user", ["twitter_id"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_twitter_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
